# Generated by Django 3.1.2 on 2020-10-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Squirrel_ID', models.CharField(help_text='Unique ID of the squirrel', max_length=100)),
                ('Date', models.DateField(help_text='Date')),
            ],
        ),
    ]
