# Generated by Django 3.1.2 on 2020-10-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Squirrel_ID',
            new_name='Unique_Squirrel_ID',
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Latitude',
            field=models.FloatField(default=0.0, help_text='Latitude'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Longitude',
            field=models.FloatField(default=0.0, help_text='Longitude'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Other_Activities',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Runs_From',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Specific_Location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_Flags',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Tail_Twitches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
